### ISSUE TITLE
Adicionar os Timers 10 e 11 ao projeto

### ISSUE THREAD

**Issue by FMorschel** [victordeckmann/psicapisca#1]
# titulo
### terceiro nivel

- item 1
- item 2

Essa frase [contem um link](https://github.com/victordeckmann/psicapisca/issues)

- [ ] precisa adicionar o timer 10
- [ ] precisa adicionar o timer 11
- [ ] precisa ligar os clocks de ambos
- [ ] precisa definir os PSCs e ARRs

<img width="246" alt="image" src="https://github.com/victordeckmann/psicapisca/assets/52160996/6be51085-f7c7-489d-b81c-827182ce6367">

Quero mostrar a variavel `TIM10` em formato de codigo

```c
void reseta(TIM_TypeDef * TIM) {
    TIM->SR &= ~TIM_SR_UIF;
}
```

**Comment by victordeckmann** [comment]
qualquer coisa

**Comment by FMorschel** [comment]
> qualquer coisa

Pois é
